//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atalasoft.Demo.PdfViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atalasoft.Demo.PdfViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to location the activation utility on this system.
        ///Please run it from the start menu..
        /// </summary>
        internal static string ActivationToolkitNotFoundMessage {
            get {
                return ResourceManager.GetString("ActivationToolkitNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookmarkGray {
            get {
                object obj = ResourceManager.GetObject("BookmarkGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookmarkTabImage {
            get {
                object obj = ResourceManager.GetObject("BookmarkTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDF file does not contain text data..
        /// </summary>
        internal static string NoTextDataMessage {
            get {
                return ResourceManager.GetString("NoTextDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PagesTabImage {
            get {
                object obj = ResourceManager.GetObject("PagesTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to view and save PDF files with DotImage and DotImage PDFRasterizer.  Rasterizers a small thumbnail of each page in the PDF asynchronously while loading the first page in the PDF.  Demonstrates use of the ThumbnailView control.
        ///
        ///.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atalasoft PDF Viewer Demo.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo require a license for {0}.
        ///An evaluation license can be requested with our activation utility.
        ///
        ///Would you like to run this utility now?.
        /// </summary>
        internal static string RequiresLicenseMessage {
            get {
                return ResourceManager.GetString("RequiresLicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found..
        /// </summary>
        internal static string TextNotFoundMessage {
            get {
                return ResourceManager.GetString("TextNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Atalasoft PDF Viewer Demo.
        /// </summary>
        internal static string TitleAboutForm {
            get {
                return ResourceManager.GetString("TitleAboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtalasoftToolkitActivation.exe Not Found.
        /// </summary>
        internal static string TitleActivationToolkitNotFoundMessage {
            get {
                return ResourceManager.GetString("TitleActivationToolkitNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text Data.
        /// </summary>
        internal static string TitleNoTextDataMessage {
            get {
                return ResourceManager.GetString("TitleNoTextDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} License Required.
        /// </summary>
        internal static string TitleRequiresLicenseMessage {
            get {
                return ResourceManager.GetString("TitleRequiresLicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Viewer Search.
        /// </summary>
        internal static string TitleSearchMessage {
            get {
                return ResourceManager.GetString("TitleSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Error.
        /// </summary>
        internal static string UpgradeErrorMessage {
            get {
                return ResourceManager.GetString("UpgradeErrorMessage", resourceCulture);
            }
        }
    }
}
